# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a707d3bb3d4e17a75fe59b8548bf652c01163fce29bf589ea88ab03b57c67da91ab4b79591ce33cbf4dea9f00366fe4f07d68c9fba89bb9cb686a5aa906316d2

test:
  secret_key_base: 3bc13f686c69434971c8ca4f64b26abb5f11fc1c83c346a5e210cb086b1458a8fc723d07f7a11294c0af9ce9a7990db5f329616f95dc466fc1d71631fca58b64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
